// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeisjJ2kE-1KGupkfJCCfnWK6G-l_zmFA',
    appId: '1:203402620214:web:1cf05ed3af36d5098ad797',
    messagingSenderId: '203402620214',
    projectId: 'loose-leaf-aaf0e',
    authDomain: 'loose-leaf-aaf0e.firebaseapp.com',
    storageBucket: 'loose-leaf-aaf0e.firebasestorage.app',
    measurementId: 'G-JBMBYNYKHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVHtWl6TQUkWO9Y2KUbJE5vK4VOpWNgco',
    appId: '1:203402620214:android:7c72aae006bab9c28ad797',
    messagingSenderId: '203402620214',
    projectId: 'loose-leaf-aaf0e',
    storageBucket: 'loose-leaf-aaf0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv9fsdHz22Q-ZOjNQpHZcIKyGqo8wh-lI',
    appId: '1:203402620214:ios:40d189baa105e8ad8ad797',
    messagingSenderId: '203402620214',
    projectId: 'loose-leaf-aaf0e',
    storageBucket: 'loose-leaf-aaf0e.firebasestorage.app',
    iosBundleId: 'com.example.noteAppWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv9fsdHz22Q-ZOjNQpHZcIKyGqo8wh-lI',
    appId: '1:203402620214:ios:40d189baa105e8ad8ad797',
    messagingSenderId: '203402620214',
    projectId: 'loose-leaf-aaf0e',
    storageBucket: 'loose-leaf-aaf0e.firebasestorage.app',
    iosBundleId: 'com.example.noteAppWithFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeisjJ2kE-1KGupkfJCCfnWK6G-l_zmFA',
    appId: '1:203402620214:web:5c2f5d854cd032328ad797',
    messagingSenderId: '203402620214',
    projectId: 'loose-leaf-aaf0e',
    authDomain: 'loose-leaf-aaf0e.firebaseapp.com',
    storageBucket: 'loose-leaf-aaf0e.firebasestorage.app',
    measurementId: 'G-ELD3EMHZQR',
  );
}
